apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170290394
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170290394
    app.kubernetes.io/part-of: test-app-170290394
  name: java-quarkus-170290394
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170290394
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170290394
    spec:
      containers:
      - image: quay.io/hacdev/oqhrvucx-tenant/test-app-170290394/java-quarkus-170290394@sha256:f160b7685cd2e41b6c49624f810989a26ca558d8dd5c26cdf04ef029520b6f08
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
